<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MockApplication.Domain\MockApplication.Domain.csproj" />
    <ProjectReference Include="..\MockApplication.Infrastructure\MockApplication.Infrastructure.csproj" />
  </ItemGroup>

</Project>
